apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: registry
  name: registry-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
