apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: homepage-config
    files:
      - settings.yaml=config/settings.yaml
      - services.yaml=config/services.yaml
      - bookmarks.yaml=config/bookmarks.yaml
      - widgets.yaml=config/widgets.yaml
      - kubernetes.yaml=config/kubernetes.yaml
      - docker.yaml=config/docker.yaml
      - custom.css=config/custom.css

generatorOptions:
  disableNameSuffixHash: false

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
