apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vaultwarden
  name: vaultwarden-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
