apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github-app.enc.yaml
  - github-app-stjohnb.enc.yaml
  - service.yaml
  - endpoints.yaml
  - ingress.yaml
  - rbac.yaml
  - statefulset-staging.yaml
  - service-staging.yaml
  - ingress-staging.yaml
