# Shared reconciler sidecar for Sonarr and Radarr. Mounted read-only at
# /scripts/reconcile.py from the servarr-reconciler-script ConfigMap
# (generated by apps/kustomization.yaml). See docs/servarr.md.
#
# Four jobs, every 300s against localhost:<API_PORT>/api/v3:
#   1. Config self-heal: re-create the root folder and the Transmission
#      download client if a DB reset lost them (#728). Transmission has no RPC
#      auth (#921), so the download-client body carries no username/password.
#   2. Import-blocked queue items: expose them as metrics (the "Servarr Import
#      Blocked" alert) and auto-import the unambiguous "matched to series/movie
#      by ID" case, exactly as a human would via Interactive Import.
#   3. Stalled Seerr/Overseerr requests: re-monitor requested seasons that are
#      unmonitored, run at most one release search per series/movie per day,
#      and expose the outcome (the "Servarr Request Unavailable" alert).
#   4. Jellyfin "Connect" entry: Sonarr/Radarr call Jellyfin's
#      Library/Media/Updated on import/upgrade/rename/delete, so Seerr sees new
#      media on its next poll instead of after the hourly Jellyfin scan
#      (~95 min lag without it).
#
# Required env (set per-service in each Deployment):
#   APP             - sonarr / radarr (also selects the Jellyfin trigger flags)
#   APIKEY          - *arr API key (servarr-apikeys secret)
#   API_PORT        - 8989 (Sonarr) / 7878 (Radarr)
#   ROOT_FOLDER     - /tv (Sonarr) / /movies (Radarr)
#   CATEGORY_FIELD  - tvCategory (Sonarr) / movieCategory (Radarr)
#   CATEGORY_VALUE  - tv-sonarr (Sonarr) / radarr (Radarr)
#   JELLYFIN_LIBRARY_PATH - /media/TV (Sonarr) / /media/Movies (Radarr): the
#                     Jellyfin-side path of ROOT_FOLDER, used as mapTo
# Optional env:
#   JELLYFIN_API_KEY    - jellyfin-api-key secret; when empty only the
#                         Jellyfin connection job is skipped (logged once)
#   REQUEST_APPS        - name=url,... request apps to poll for approved requests
#   SEERR_API_KEY, OVERSEERR_API_KEY - <NAME>_API_KEY per REQUEST_APPS entry
#   STALLED_AFTER_DAYS  - grace period before a request counts as stalled (3)
#   STATE_FILE          - persisted caps/first-seen times (/state/reconciler-state.json)
#   METRICS_PORT        - Prometheus /metrics port (9101)
import datetime
import http.server
import json
import os
import re
import threading
import time
import urllib.parse
import urllib.request

INTERVAL = 300
IMPORT_RETRY_SECONDS = 3600
SEARCH_INTERVAL_SECONDS = 86400
DEFAULT_TIMEOUT = 30
QUEUE_PAGE_SIZE = 200
MAX_QUEUE_PAGES = 50
RELEASE_TIMEOUT = 180
BY_ID_RE = re.compile(r"matched to (series|movie) by ID")
BLOCKED_STATES = ("importBlocked", "importPending")
JELLYFIN_HOST = "jellyfin.default.svc.cluster.local"
# (events that notify Jellyfin, events that must not) per app.
JELLYFIN_EVENTS = {
    "sonarr": (
        ("onDownload", "onUpgrade", "onImportComplete", "onRename",
         "onSeriesDelete", "onEpisodeFileDelete",
         "onEpisodeFileDeleteForUpgrade"),
        ("onGrab", "onSeriesAdd", "onHealthIssue", "onHealthRestored",
         "includeHealthWarnings", "onApplicationUpdate",
         "onManualInteractionRequired"),
    ),
    "radarr": (
        ("onDownload", "onUpgrade", "onRename", "onMovieDelete",
         "onMovieFileDelete", "onMovieFileDeleteForUpgrade"),
        ("onGrab", "onMovieAdded", "onHealthIssue", "onHealthRestored",
         "includeHealthWarnings", "onApplicationUpdate",
         "onManualInteractionRequired"),
    ),
}


def log(msg):
    print("reconciler: " + msg, flush=True)


# --------------------------------------------------------------------------
# Pure helpers (unit-tested in test_reconcile.py)
# --------------------------------------------------------------------------

def is_blocked(record):
    """A queue record that is waiting on an import that is not happening."""
    if record.get("trackedDownloadState") in BLOCKED_STATES:
        return True
    return (record.get("status") == "completed"
            and record.get("trackedDownloadStatus") == "warning")


def status_messages(record):
    out = []
    for sm in record.get("statusMessages") or []:
        for msg in sm.get("messages") or []:
            if msg and msg not in out:
                out.append(msg)
    return out


def is_by_id_only(record):
    """Blocked solely because the release was matched to series/movie by ID."""
    msgs = status_messages(record)
    return bool(msgs) and all(BY_ID_RE.search(m) for m in msgs)


def block_reason(record):
    msgs = status_messages(record)
    if msgs:
        return msgs[0]
    return (record.get("errorMessage")
            or record.get("trackedDownloadState")
            or record.get("trackedDownloadStatus")
            or "unknown")


def merge_queue_records(records):
    """Group blocked queue records by downloadId. Sonarr emits one record per
    episode of a season pack; all of them share the download."""
    items = {}
    for rec in records:
        if not is_blocked(rec):
            continue
        did = rec.get("downloadId")
        if not did:
            continue
        item = items.get(did)
        if item is None:
            item = dict(rec)
            item["statusMessages"] = list(rec.get("statusMessages") or [])
            items[did] = item
        else:
            item["statusMessages"].extend(rec.get("statusMessages") or [])
    return items


def import_plan(item, proposals, app):
    """Return (files, reason). files is the ManualImport `files` list when the
    proposal is unambiguous, otherwise None and reason says why."""
    if not proposals:
        return None, "empty proposal"
    owner = "series" if app == "sonarr" else "movie"
    want = item.get(owner + "Id")
    if not want:
        return None, "queue item has no %sId" % owner
    files = []
    seen_episodes = set()
    for p in proposals:
        if p.get("rejections"):
            return None, "rejections on %s: %s" % (
                p.get("relativePath") or p.get("path"),
                "; ".join(r.get("reason", "") if isinstance(r, dict) else str(r)
                          for r in p["rejections"]))
        target = p.get(owner) or {}
        if target.get("id") != want:
            return None, "%s mismatch (proposal %s, grab history %s)" % (
                owner, target.get("id"), want)
        f = {
            "path": p.get("path"),
            "folderName": p.get("folderName"),
            "quality": p.get("quality"),
            "languages": p.get("languages"),
            "releaseGroup": p.get("releaseGroup"),
            "indexerFlags": p.get("indexerFlags", 0),
            "downloadId": p.get("downloadId") or item.get("downloadId"),
        }
        if app == "sonarr":
            episodes = p.get("episodes") or []
            if len(episodes) != 1:
                return None, "%d episodes for %s" % (
                    len(episodes), p.get("relativePath") or p.get("path"))
            eid = episodes[0].get("id")
            if eid in seen_episodes:
                return None, "two files map to episode %s" % eid
            seen_episodes.add(eid)
            f["seriesId"] = want
            f["episodeIds"] = [eid]
            f["releaseType"] = p.get("releaseType")
        else:
            f["movieId"] = want
        files.append(f)
    return files, "unambiguous"


def season_first_aired(episodes, now):
    """{seasonNumber: earliest airDateUtc <= now} over every episode, monitored
    or not. Sonarr's statistics.previousAiring ignores unmonitored episodes,
    so an unmonitored season would never look aired from statistics alone."""
    out = {}
    for ep in episodes or []:
        num = ep.get("seasonNumber")
        ts = parse_time(ep.get("airDateUtc"))
        if num is None or ts is None or ts > now:
            continue
        if num not in out or ts < out[num]:
            out[num] = ts
    return out


def missing_requested_seasons(series, seasons, aired=None):
    """Requested season numbers with no episode files (episodeFileCount counts
    all episodes, monitored or not) that have aired per `aired` (from
    season_first_aired). With aired=None the air check is skipped."""
    out = []
    by_num = {s.get("seasonNumber"): s for s in series.get("seasons") or []}
    for num in sorted(set(seasons)):
        s = by_num.get(num)
        if s is None or (aired is not None and num not in aired):
            continue
        stats = s.get("statistics") or {}
        if stats.get("episodeFileCount", 0) == 0:
            out.append(num)
    return out


def top_rejections(results, limit=3, width=200):
    counts = {}
    order = []
    for r in results:
        for rej in r.get("rejections") or []:
            if rej not in counts:
                counts[rej] = 0
                order.append(rej)
            counts[rej] += 1
    if not order:
        return "no results from indexers" if not results else ""
    ranked = sorted(order, key=lambda k: (-counts[k], order.index(k)))[:limit]
    return "; ".join(ranked)[:width]


def classify_search(results):
    """'searching' when an acceptable release exists, else
    'no_acceptable_release'."""
    if any(r.get("rejected") is False for r in results):
        return "searching"
    return "no_acceptable_release"


def parse_time(value):
    """Epoch seconds from the *arr ISO-8601 timestamps (.NET emits up to 7
    fractional digits, which fromisoformat rejects), or None."""
    if not value:
        return None
    m = re.match(r"^(\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d)(?:\.(\d+))?(Z|[+-]\d\d:\d\d)?$",
                 value.strip())
    if not m:
        return None
    text = m.group(1)
    if m.group(2):
        text += "." + m.group(2)[:6].ljust(6, "0")
    tz = m.group(3)
    if tz and tz != "Z":
        text += tz
    try:
        dt = datetime.datetime.fromisoformat(text)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    return dt.timestamp()


def merge_requests(requests, media_type):
    """Approved, non-4k requests of media_type: {tvdbId: {season: requested}}
    or {tmdbId: requested}, where requested is the earliest request createdAt
    (0 when unknown). The grace period starts at the request, not at the date
    the series/movie entered the library."""
    out = {}
    for r in requests:
        if r.get("is4k") or r.get("type") != media_type:
            continue
        media = r.get("media") or {}
        created = parse_time(r.get("createdAt")) or 0
        if media_type == "tv":
            key = media.get("tvdbId")
            if not key:
                continue
            seasons = out.setdefault(key, {})
            for s in r.get("seasons") or []:
                num = s.get("seasonNumber")
                if num is not None:
                    seasons[num] = min(seasons.get(num, created), created)
        else:
            key = media.get("tmdbId")
            if key:
                out[key] = min(out.get(key, created), created)
    return out


def next_season(missing, last):
    """Rotate through the stalled seasons, so one season that never has an
    acceptable release cannot starve the others of their daily search."""
    if last is not None:
        for n in missing:
            if n is not None and n > last:
                return n
    return missing[0]


def display_title(obj):
    title = obj.get("title") or ""
    year = obj.get("year")
    if title and year and not title.endswith("(%s)" % year):
        title = "%s (%s)" % (title, year)
    return title


def escape_label(value):
    return (str(value).replace("\\", "\\\\").replace("\"", "\\\"")
            .replace("\n", "\\n"))


def jellyfin_body(app, root_folder, library_path, api_key):
    """Desired MediaBrowser Connect entry; notify is off, updateLibrary on."""
    on, off = JELLYFIN_EVENTS[app]
    body = {"name": "Jellyfin"}
    body.update((f, True) for f in on)
    body.update((f, False) for f in off)
    body.update({
        "implementation": "MediaBrowser",
        "implementationName": "Emby / Jellyfin",
        "configContract": "MediaBrowserSettings",
        "tags": [],
        "fields": [
            {"name": "host", "value": JELLYFIN_HOST},
            {"name": "port", "value": 8096},
            {"name": "useSsl", "value": False},
            {"name": "apiKey", "value": api_key},
            {"name": "notify", "value": False},
            {"name": "updateLibrary", "value": True},
            {"name": "mapFrom", "value": root_folder},
            {"name": "mapTo", "value": library_path},
        ],
    })
    return body


def jellyfin_drift(current, desired, app):
    """First visible difference between an existing entry and the desired
    body, or None. apiKey is not compared: the API masks it as "********"."""
    if current.get("name") != desired["name"]:
        return "name"
    have = {f.get("name"): f.get("value") for f in current.get("fields") or []}
    for field in desired["fields"]:
        if field["name"] != "apiKey" and have.get(field["name"]) != field["value"]:
            return field["name"]
    for flag in JELLYFIN_EVENTS[app][0]:
        if current.get(flag) is not True:
            return flag
    return None


# --------------------------------------------------------------------------
# Runtime
# --------------------------------------------------------------------------

class Reconciler:
    def __init__(self, env):
        self.app = env.get("APP", "sonarr")
        self.api = "http://localhost:%s/api/v3" % env.get("API_PORT", "8989")
        self.apikey = env.get("APIKEY", "").strip()
        self.root_folder = env.get("ROOT_FOLDER", "")
        self.category_field = env.get("CATEGORY_FIELD", "")
        self.category_value = env.get("CATEGORY_VALUE", "")
        self.jellyfin_key = env.get("JELLYFIN_API_KEY", "").strip()
        self.jellyfin_path = env.get("JELLYFIN_LIBRARY_PATH", "")
        # False until the first successful write. The API masks apiKey, so it
        # can't be compared; the entry is re-asserted once per sidecar start
        # and afterwards rewritten only on visible drift.
        self.jellyfin_asserted = False
        self.jellyfin_skip_logged = False
        self.stalled_after = float(env.get("STALLED_AFTER_DAYS", "3")) * 86400
        self.state_file = env.get("STATE_FILE", "/state/reconciler-state.json")
        self.metrics_port = int(env.get("METRICS_PORT", "9101"))
        self.request_apps = []
        for entry in (env.get("REQUEST_APPS") or "").split(","):
            if "=" not in entry:
                continue
            name, url = entry.split("=", 1)
            name = name.strip()
            key = env.get(name.upper() + "_API_KEY", "").strip()
            self.request_apps.append((name, url.strip().rstrip("/"), key))
        self.owner = "series" if self.app == "sonarr" else "movie"
        self.state = self.load_state()
        self.saved_state = json.dumps(self.state, sort_keys=True)
        self.last_decision = {}
        self.source_counts = {}
        self.lock = threading.Lock()
        self.metrics = {
            "loop": 0.0,
            "blocked": [],
            "stalled": [],
            "sources": {},
            "auto_import": {"imported": 0, "skipped": 0, "failed": 0},
            "actions": {"remonitored": 0, "season_search": 0,
                        "release_search": 0},
        }

    # -- state ---------------------------------------------------------------

    def load_state(self):
        state = {}
        try:
            with open(self.state_file) as fh:
                state = json.load(fh)
        except FileNotFoundError:
            pass
        except Exception as exc:
            log("could not read %s (%s) - starting empty" % (self.state_file, exc))
        for key in ("first_seen", "attempted", "search"):
            if not isinstance(state.get(key), dict):
                state[key] = {}
        return state

    def save_state(self):
        text = json.dumps(self.state, sort_keys=True)
        if text == self.saved_state:
            return
        tmp = self.state_file + ".tmp"
        try:
            with open(tmp, "w") as fh:
                fh.write(text)
            os.replace(tmp, self.state_file)
            self.saved_state = text
        except Exception as exc:
            log("could not write %s: %s" % (self.state_file, exc))

    # -- HTTP ----------------------------------------------------------------

    def http(self, method, url, headers, body=None, timeout=DEFAULT_TIMEOUT):
        data = None
        headers = dict(headers, Accept="application/json")
        if body is not None:
            data = json.dumps(body).encode()
            headers["Content-Type"] = "application/json"
        req = urllib.request.Request(url, data=data, headers=headers,
                                     method=method)
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            raw = resp.read()
        return json.loads(raw) if raw else None

    def arr(self, method, path, body=None, timeout=DEFAULT_TIMEOUT):
        return self.http(method, self.api + path, {"X-Api-Key": self.apikey},
                         body, timeout)

    # -- job 1: config self-heal --------------------------------------------

    def download_client_body(self):
        return {
            "enable": True,
            "protocol": "torrent",
            "priority": 1,
            "removeCompletedDownloads": True,
            "removeFailedDownloads": True,
            "name": "Transmission",
            "implementation": "Transmission",
            "implementationName": "Transmission",
            "configContract": "TransmissionSettings",
            "fields": [
                {"name": "host", "value": "transmission.default.svc.cluster.local"},
                {"name": "port", "value": 9091},
                {"name": "useSsl", "value": False},
                {"name": "urlBase", "value": "/transmission/"},
                {"name": self.category_field, "value": self.category_value},
            ],
        }

    def reconcile_config(self):
        try:
            folders = self.arr("GET", "/rootfolder") or []
        except Exception as exc:
            log("rootfolder GET failed: %s" % exc)
        else:
            if not any((f.get("path") or "").rstrip("/") == self.root_folder
                       for f in folders):
                log("adding %s root folder" % self.root_folder)
                try:
                    self.arr("POST", "/rootfolder", {"path": self.root_folder})
                except Exception as exc:
                    log("rootfolder POST failed: %s" % exc)
        try:
            clients = self.arr("GET", "/downloadclient") or []
        except Exception as exc:
            log("downloadclient GET failed: %s" % exc)
            return
        if not any("Transmission" in json.dumps(c) for c in clients):
            log("adding Transmission download client")
            try:
                self.arr("POST", "/downloadclient", self.download_client_body())
            except Exception as exc:
                log("downloadclient POST failed: %s" % exc)
            return
        # The client already exists, so the POST never runs. Rewrite it from
        # the same desired-state body instead: a client that lost its removal
        # flags (#728) would otherwise stay broken forever.
        for cid in range(1, 11):
            try:
                dc = self.arr("GET", "/downloadclient/%d" % cid)
            except Exception:
                continue
            if not dc or dc.get("implementation") != "Transmission":
                continue
            if dc.get("removeCompletedDownloads") is True and \
                    dc.get("removeFailedDownloads") is True:
                continue
            log("rewriting Transmission download client %d (removal flags off)"
                % cid)
            body = dict(self.download_client_body(), id=cid)
            try:
                self.arr("PUT", "/downloadclient/%d?forceSave=true" % cid, body)
            except Exception as exc:
                log("downloadclient PUT failed: %s" % exc)

    # -- job 4: Jellyfin connection -----------------------------------------

    def reconcile_jellyfin(self):
        if not self.jellyfin_key or self.app not in JELLYFIN_EVENTS:
            if not self.jellyfin_skip_logged:
                log("JELLYFIN_API_KEY is empty or APP=%r is unknown, skipping "
                    "Jellyfin connection" % self.app)
                self.jellyfin_skip_logged = True
            return
        desired = jellyfin_body(self.app, self.root_folder, self.jellyfin_path,
                                self.jellyfin_key)
        try:
            notifications = self.arr("GET", "/notification") or []
        except Exception as exc:
            log("notification GET failed: %s" % exc)
            return
        # The lowest-id MediaBrowser entry is the managed one, whatever its name.
        managed = sorted((n for n in notifications
                          if n.get("implementation") == "MediaBrowser"),
                         key=lambda n: n.get("id") or 0)
        if not managed:
            log("adding Jellyfin connection")
            # No forceSave: the app tests the connection, so a bad key or an
            # unreachable Jellyfin fails here and is retried next loop.
            try:
                self.arr("POST", "/notification", desired)
                self.jellyfin_asserted = True
            except Exception as exc:
                log("notification POST failed: %s" % exc)
            return
        current = managed[0]
        nid = current.get("id")
        for extra in managed[1:]:
            log("warning: extra Jellyfin connection %s ignored (managing %s)"
                % (extra.get("id"), nid))
        if not self.jellyfin_asserted:
            log("re-asserting Jellyfin connection %s (sidecar start)" % nid)
        else:
            drift = jellyfin_drift(current, desired, self.app)
            if drift is None:
                return
            log("rewriting Jellyfin connection %s (drift: %s)" % (nid, drift))
        try:
            self.arr("PUT", "/notification/%s?forceSave=true" % nid,
                     dict(desired, id=nid))
            self.jellyfin_asserted = True
        except Exception as exc:
            log("notification PUT failed: %s" % exc)

    # -- job 2: import-blocked queue ----------------------------------------

    def decide(self, did, result, reason, title):
        # A blocked item is re-evaluated every loop; log and count a skip only
        # when the decision changes, so neither the log nor the counter grows
        # every 5 minutes for the same stuck download.
        if result == "skipped" and self.last_decision.get(did) == (result, reason):
            return
        self.last_decision[did] = (result, reason)
        log("auto-import %s %s %r: %s" % (result, did, title, reason))
        with self.lock:
            self.metrics["auto_import"][result] += 1

    def reconcile_queue(self):
        unknown = ("includeUnknownSeriesItems" if self.app == "sonarr"
                   else "includeUnknownMovieItems")
        records = []
        for page_no in range(1, MAX_QUEUE_PAGES + 1):
            page = self.arr("GET", "/queue?page=%d&pageSize=%d&%s=true" % (
                page_no, QUEUE_PAGE_SIZE, unknown)) or {}
            got = page.get("records") or []
            records.extend(got)
            if not got or len(records) >= (page.get("totalRecords") or 0):
                break
        items = merge_queue_records(records)
        now = time.time()
        first_seen = self.state["first_seen"]
        attempted = self.state["attempted"]
        for did in list(first_seen):
            if did not in items:
                del first_seen[did]
        for did in list(attempted):
            if did not in items and now - attempted[did] > IMPORT_RETRY_SECONDS:
                del attempted[did]
        for did in list(self.last_decision):
            if did not in items:
                del self.last_decision[did]
        blocked = []
        for did, item in items.items():
            first_seen.setdefault(did, now)
            blocked.append({
                "download_id": did,
                "title": item.get("title") or did,
                "reason": block_reason(item)[:160],
                "seconds": now - first_seen[did],
            })
        # Publish before any auto-import work, so a failing lookup below can
        # never hide a blocked download from the alert.
        with self.lock:
            self.metrics["blocked"] = blocked
        for did, item in items.items():
            title = item.get("title") or did
            if not is_by_id_only(item):
                self.decide(did, "skipped", "not a by-ID match: %s"
                            % block_reason(item)[:160], title)
                continue
            if now - attempted.get(did, 0) < IMPORT_RETRY_SECONDS:
                self.decide(did, "skipped", "attempted within the last hour",
                            title)
                continue
            try:
                proposals = self.arr(
                    "GET", "/manualimport?downloadId=%s&filterExistingFiles=true"
                    % urllib.parse.quote(did))
                files, reason = import_plan(item, proposals or [], self.app)
            except Exception as exc:
                # A lookup that 500s or times out (files gone, slow NAS scan)
                # counts as an attempt, so it is retried hourly, not per loop.
                attempted[did] = now
                self.decide(did, "failed", "manualimport GET: %s" % exc, title)
                continue
            if files is None:
                self.decide(did, "skipped", reason, title)
                continue
            attempted[did] = now
            self.save_state()
            try:
                self.arr("POST", "/command", {
                    "name": "ManualImport",
                    "importMode": "auto",
                    "files": files,
                })
            except Exception as exc:
                self.decide(did, "failed", "ManualImport POST: %s" % exc, title)
                continue
            self.decide(did, "imported", "%d file(s), %s" % (len(files), reason),
                        title)

    # -- job 3: stalled requests ---------------------------------------------

    def fetch_requests(self):
        """(requests, complete): all approved requests from every reachable
        request app, or None if no source could be read (so nothing is
        mistaken for 'no requests'). complete is False when any source with a
        key failed, i.e. the list is a partial view."""
        merged = []
        ok = False
        complete = True
        up = {}
        for name, url, key in self.request_apps:
            up[name] = 0
            if not key:
                log("no key for %s - skipping that request source" % name)
                continue
            got = []
            try:
                skip = 0
                while True:
                    page = self.http(
                        "GET", "%s/api/v1/request?filter=approved&take=100&skip=%d"
                        % (url, skip), {"X-Api-Key": key})
                    got.extend(page.get("results") or [])
                    info = page.get("pageInfo") or {}
                    skip += 100
                    if (info.get("page") or 1) >= (info.get("pages") or 1) \
                            or not page.get("results"):
                        break
            except Exception as exc:
                log("request source %s unreachable: %s" % (name, exc))
                complete = False
                continue
            ok = True
            up[name] = 1
            merged.extend(got)
            if self.source_counts.get(name) != len(got):
                log("request source %s: %d approved requests" % (name, len(got)))
                self.source_counts[name] = len(got)
        with self.lock:
            self.metrics["sources"] = up
        return (merged if ok else None), complete

    def grabbed_since(self, obj, season, since):
        if self.app == "sonarr":
            path = "/history/series?seriesId=%d&seasonNumber=%d&eventType=1" % (
                obj["id"], season)
        else:
            path = "/history/movie?movieId=%d&eventType=1" % obj["id"]
        records = self.arr("GET", path) or []
        if isinstance(records, dict):
            records = records.get("records") or []
        for rec in records:
            ts = parse_time(rec.get("date"))
            if ts is not None and ts >= since:
                return True
        return False

    def stalled_seasons(self, series, seasons, now):
        """Requested seasons of one series that are stalled. The grace period
        starts at the latest of: series added, season requested, season first
        aired - so a new request on an old series, or a season that started
        airing today, is not stalled yet."""
        added = parse_time(series.get("added"))
        if added is None:
            return []
        # Only fetch episodes when some requested season has no files at all.
        empty = missing_requested_seasons(series, seasons)
        if not empty:
            return []
        aired = season_first_aired(
            self.arr("GET", "/episode?seriesId=%d" % series["id"]), now)
        missing = []
        for num in missing_requested_seasons(series, empty, aired):
            since = max(added, seasons[num], aired[num])
            if now - since < self.stalled_after:
                continue
            if not self.grabbed_since(series, num, since):
                missing.append(num)
        return missing

    def stalled_candidates(self, requests, now):
        """([(obj, seasons_missing)], evaluated, failed) for every
        request-covered series/movie that is past the grace period, missing
        files, and has no grab since the grace period started. evaluated holds
        the ids whose status is known this loop (stalled or not); failed holds
        the ids whose per-item lookup raised."""
        out = []
        evaluated = set()
        failed = set()
        if self.app == "sonarr":
            wanted = merge_requests(requests, "tv")
            library = self.arr("GET", "/series") or []
            for series in library:
                seasons = wanted.get(series.get("tvdbId"))
                if not seasons:
                    continue
                try:
                    missing = self.stalled_seasons(series, seasons, now)
                except Exception as exc:
                    log("stalled check %r failed: %s" % (series.get("title"), exc))
                    failed.add(str(series.get("id")))
                    continue
                evaluated.add(str(series.get("id")))
                if missing:
                    out.append((series, missing))
        else:
            wanted = merge_requests(requests, "movie")
            library = self.arr("GET", "/movie") or []
            for movie in library:
                if movie.get("tmdbId") not in wanted:
                    continue
                key = str(movie.get("id"))
                if movie.get("hasFile") or not movie.get("isAvailable"):
                    evaluated.add(key)
                    continue
                added = parse_time(movie.get("added"))
                since = max(added or 0, wanted[movie["tmdbId"]])
                if added is None or now - since < self.stalled_after:
                    evaluated.add(key)
                    continue
                try:
                    grabbed = self.grabbed_since(movie, 0, since)
                except Exception as exc:
                    log("stalled check %r failed: %s" % (movie.get("title"), exc))
                    failed.add(key)
                    continue
                evaluated.add(key)
                if not grabbed:
                    out.append((movie, [None]))
        return out, evaluated, failed

    def remonitor(self, obj, missing):
        """Re-monitor exactly the missing requested seasons (and the series
        itself); returns True when it wrote."""
        if self.app == "sonarr":
            changed = not obj.get("monitored")
            obj["monitored"] = True
            for s in obj.get("seasons") or []:
                if s.get("seasonNumber") in missing and not s.get("monitored"):
                    s["monitored"] = True
                    changed = True
            if not changed:
                return False
            self.arr("PUT", "/series/%d" % obj["id"], obj)
        else:
            if obj.get("monitored"):
                return False
            obj["monitored"] = True
            self.arr("PUT", "/movie/%d" % obj["id"], obj)
        with self.lock:
            self.metrics["actions"]["remonitored"] += 1
        log("re-monitored %r %s" % (obj.get("title"), "seasons %s" % missing
                                    if self.app == "sonarr" else ""))
        return True

    def search(self, obj, season):
        """One non-grabbing release search, then a real search command only
        when something acceptable exists. Returns the stored result."""
        with self.lock:
            self.metrics["actions"]["release_search"] += 1
        if self.app == "sonarr":
            path = "/release?seriesId=%d&seasonNumber=%d" % (obj["id"], season)
            command = {"name": "SeasonSearch", "seriesId": obj["id"],
                       "seasonNumber": season}
        else:
            path = "/release?movieId=%d" % obj["id"]
            command = {"name": "MoviesSearch", "movieIds": [obj["id"]]}
        result = {"reason": "search_failed", "rejections": ""}
        try:
            results = self.arr("GET", path, timeout=RELEASE_TIMEOUT) or []
        except Exception as exc:
            result["rejections"] = ("release search: %s" % exc)[:200]
            return result
        result["reason"] = classify_search(results)
        if result["reason"] == "searching":
            try:
                self.arr("POST", "/command", command)
                with self.lock:
                    self.metrics["actions"]["season_search"] += 1
            except Exception as exc:
                result = {"reason": "search_failed",
                          "rejections": ("%s: %s" % (command["name"], exc))[:200]}
        else:
            result["rejections"] = top_rejections(results)
        return result

    def reconcile_requests(self):
        if not self.request_apps:
            return
        now = time.time()
        requests, sources_complete = self.fetch_requests()
        if requests is None:
            # Nothing could be read: every item's status is unknown.
            self.publish_stalled([], set(), set(), False, now)
            return
        try:
            candidates, evaluated, failed = self.stalled_candidates(requests, now)
        except Exception:
            self.publish_stalled([], set(), set(), False, now)
            raise
        searches = self.state["search"]
        live = {str(obj["id"]) for obj, _ in candidates}
        # Prune by age, never by absence alone: an item that drops out for one
        # loop (request app restarting, a failed lookup) must keep its daily
        # search cap and its last result.
        for key in list(searches):
            if key not in live and \
                    now - searches[key].get("last_search", 0) >= SEARCH_INTERVAL_SECONDS:
                del searches[key]
        remonitored = set()
        for obj, missing in candidates:
            key = str(obj["id"])
            try:
                if self.remonitor(obj, [m for m in missing if m is not None]):
                    remonitored.add(key)
                    # Keep reporting "unmonitored" until the first search
                    # replaces it, even if that search is a few loops away.
                    searches.setdefault(key, {"reason": "unmonitored",
                                              "rejections": "",
                                              "last_search": 0})
            except Exception as exc:
                log("re-monitor %r failed: %s" % (obj.get("title"), exc))
        # At most one release search per loop, oldest first, and never the
        # same series/movie twice within SEARCH_INTERVAL_SECONDS.
        due = [(searches.get(str(obj["id"]), {}).get("last_search", 0), obj,
                missing) for obj, missing in candidates]
        due = [d for d in due if now - d[0] >= SEARCH_INTERVAL_SECONDS]
        if due:
            due.sort(key=lambda d: d[0])
            _, obj, missing = due[0]
            season = next_season(
                missing, searches.get(str(obj["id"]), {}).get("season"))
            result = self.search(obj, season)
            result["last_search"] = now
            result["season"] = season
            searches[str(obj["id"])] = result
            log("searched %r%s: %s %s" % (
                obj.get("title"),
                " season %s" % season if season is not None else "",
                result["reason"], result.get("rejections", "")))
        stalled = []
        for obj, missing in candidates:
            key = str(obj["id"])
            if key in remonitored:
                reason, rejections = "unmonitored", ""
            elif key in searches:
                reason = searches[key]["reason"]
                rejections = searches[key].get("rejections", "")
            else:
                continue  # awaiting its first search
            title = display_title(obj) or key
            stalled.append({"id": key, "seen": now, "title": title,
                            "reason": reason, "rejections": rejections})
        self.publish_stalled(stalled, evaluated, failed, sources_complete, now)

    def publish_stalled(self, fresh, evaluated, failed, sources_complete, now):
        """Merge this loop's stalled entries with the previous ones per item.
        An item this loop could evaluate gets its fresh status (or drops out).
        An item whose status is unknown - its lookup raised, or it may be
        covered only by a request source that failed - keeps its previous
        entry, so a request app restart cannot resolve and re-fire its alert,
        but only for SEARCH_INTERVAL_SECONDS after it was last evaluated, so a
        source that is gone for good cannot pin an alert forever."""
        fresh_ids = {e["id"] for e in fresh}
        with self.lock:
            previous = self.metrics["stalled"]
        carried = []
        for e in previous:
            if e["id"] in fresh_ids or e["id"] in evaluated:
                continue
            if sources_complete and e["id"] not in failed:
                continue  # every source answered and no longer covers it
            if now - e["seen"] >= SEARCH_INTERVAL_SECONDS:
                log("dropping stale stalled entry %r" % e["title"])
                continue
            carried.append(e)
        if carried:
            log("status unknown for %d stalled item(s) - kept their last entry"
                % len(carried))
        with self.lock:
            self.metrics["stalled"] = fresh + carried

    # -- metrics -------------------------------------------------------------

    def render_metrics(self):
        app = escape_label(self.app)
        with self.lock:
            m = json.loads(json.dumps(self.metrics))
        lines = [
            "# HELP servarr_reconciler_up Sidecar liveness.",
            "# TYPE servarr_reconciler_up gauge",
            'servarr_reconciler_up{app="%s"} 1' % app,
            "# HELP servarr_reconciler_last_loop_timestamp_seconds Last completed loop.",
            "# TYPE servarr_reconciler_last_loop_timestamp_seconds gauge",
            'servarr_reconciler_last_loop_timestamp_seconds{app="%s"} %.0f'
            % (app, m["loop"]),
            "# HELP servarr_queue_import_blocked_seconds Seconds a queue item has been import-blocked.",
            "# TYPE servarr_queue_import_blocked_seconds gauge",
        ]
        for b in m["blocked"]:
            lines.append(
                'servarr_queue_import_blocked_seconds{app="%s",download_id="%s",'
                'title="%s",reason="%s"} %.0f' % (
                    app, escape_label(b["download_id"]), escape_label(b["title"]),
                    escape_label(b["reason"]), b["seconds"]))
        lines += [
            "# HELP servarr_auto_import_total Auto-import decisions since start.",
            "# TYPE servarr_auto_import_total counter",
        ]
        for result, n in sorted(m["auto_import"].items()):
            lines.append('servarr_auto_import_total{app="%s",result="%s"} %d'
                         % (app, result, n))
        lines += [
            "# HELP servarr_request_stalled Approved request with no file past the grace period.",
            "# TYPE servarr_request_stalled gauge",
        ]
        for s in m["stalled"]:
            lines.append(
                'servarr_request_stalled{app="%s",title="%s",reason="%s",'
                'rejections="%s"} 1' % (
                    app, escape_label(s["title"]), escape_label(s["reason"]),
                    escape_label(s["rejections"])))
        lines += [
            "# HELP servarr_request_source_up Whether the last poll of a request app succeeded (0 also when it has no API key).",
            "# TYPE servarr_request_source_up gauge",
        ]
        for source, up in sorted(m["sources"].items()):
            lines.append('servarr_request_source_up{app="%s",source="%s"} %d'
                         % (app, escape_label(source), up))
        lines += [
            "# HELP servarr_request_actions_total Writes and searches made for stalled requests since start.",
            "# TYPE servarr_request_actions_total counter",
        ]
        for action, n in sorted(m["actions"].items()):
            lines.append('servarr_request_actions_total{app="%s",action="%s"} %d'
                         % (app, action, n))
        return "\n".join(lines) + "\n"

    def start_metrics_server(self):
        reconciler = self

        class Handler(http.server.BaseHTTPRequestHandler):
            protocol_version = "HTTP/1.0"

            def do_GET(self):
                if self.path.split("?")[0] != "/metrics":
                    self.send_response(404)
                    self.end_headers()
                    return
                body = reconciler.render_metrics().encode()
                self.send_response(200)
                self.send_header("Content-Type", "text/plain; version=0.0.4")
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)

            def log_message(self, *args):
                # One line per scrape would drown the reconciler's own log.
                pass

        srv = http.server.ThreadingHTTPServer(("", self.metrics_port), Handler)
        threading.Thread(target=srv.serve_forever, daemon=True).start()
        log("serving metrics on :%d/metrics" % self.metrics_port)

    # -- loop ----------------------------------------------------------------

    def run_once(self):
        try:
            self.arr("GET", "/system/status")
        except Exception:
            return  # app still starting; try again next loop
        for fn in (self.reconcile_config, self.reconcile_queue,
                   self.reconcile_requests, self.reconcile_jellyfin):
            try:
                fn()
            except Exception as exc:
                log("%s failed: %s" % (fn.__name__, exc))
        self.save_state()
        with self.lock:
            self.metrics["loop"] = time.time()

    def run(self):
        self.start_metrics_server()
        while True:
            self.run_once()
            time.sleep(INTERVAL)


def main():
    Reconciler(dict(os.environ)).run()


if __name__ == "__main__":
    main()
