#!/bin/sh
# Shared config-reconciler for Sonarr and Radarr. Mounted read-only at
# /scripts/reconcile.sh from the servarr-reconciler-script ConfigMap
# (generated by apps/kustomization.yaml). See docs/servarr.md.
#
# Required env (set per-service in each Deployment):
#   APIKEY          - *arr API key (servarr-apikeys secret)
#   API_PORT        - 8989 (Sonarr) / 7878 (Radarr)
#   ROOT_FOLDER     - /tv (Sonarr) / /movies (Radarr)
#   CATEGORY_FIELD  - tvCategory (Sonarr) / movieCategory (Radarr)
#   CATEGORY_VALUE  - tv-sonarr (Sonarr) / radarr (Radarr)
#
# Transmission has no RPC auth (#921) — the download-client body deliberately
# carries no username/password fields.

API="http://localhost:${API_PORT}/api/v3"
AUTH="X-Api-Key: ${APIKEY}"
CT="Content-Type: application/json"

cat > /tmp/dc.json <<JSON
{
  "enable": true,
  "protocol": "torrent",
  "priority": 1,
  "removeCompletedDownloads": true,
  "removeFailedDownloads": true,
  "name": "Transmission",
  "implementation": "Transmission",
  "implementationName": "Transmission",
  "configContract": "TransmissionSettings",
  "fields": [
    {"name": "host", "value": "transmission.default.svc.cluster.local"},
    {"name": "port", "value": 9091},
    {"name": "useSsl", "value": false},
    {"name": "urlBase", "value": "/transmission/"},
    {"name": "${CATEGORY_FIELD}", "value": "${CATEGORY_VALUE}"}
  ]
}
JSON

while true; do
  if curl -sf -o /dev/null -H "$AUTH" "$API/system/status"; then
    if FOLDERS=$(curl -sf -H "$AUTH" "$API/rootfolder"); then
      echo "$FOLDERS" | grep -q "\"${ROOT_FOLDER}\"" || {
        echo "reconciler: adding ${ROOT_FOLDER} root folder"
        curl -sf -o /dev/null -X POST -H "$AUTH" -H "$CT" -d "{\"path\":\"${ROOT_FOLDER}\"}" "$API/rootfolder" \
          || echo "reconciler: rootfolder POST failed"
      }
    fi
    if CLIENTS=$(curl -sf -H "$AUTH" "$API/downloadclient"); then
      if echo "$CLIENTS" | grep -q 'Transmission'; then
        # The client already exists, so the POST below never runs. Rewrite it
        # from the same desired-state body instead: a client that lost its
        # removal flags (#728) would otherwise stay broken forever.
        id=1
        while [ "$id" -le 10 ]; do
          if DC=$(curl -sf -H "$AUTH" "$API/downloadclient/$id"); then
            if echo "$DC" | grep -q '"implementation"[[:space:]]*:[[:space:]]*"Transmission"'; then
              REASON=""
              echo "$DC" | grep -q '"removeCompletedDownloads"[[:space:]]*:[[:space:]]*true' \
                || REASON="removal flags off"
              echo "$DC" | grep -q '"removeFailedDownloads"[[:space:]]*:[[:space:]]*true' \
                || REASON="removal flags off"
              if [ -n "$REASON" ]; then
                echo "reconciler: rewriting Transmission download client $id ($REASON)"
                sed "1s|^{|{\"id\": ${id},|" /tmp/dc.json > /tmp/dc-put.json
                curl -sf -o /dev/null -X PUT -H "$AUTH" -H "$CT" -d @/tmp/dc-put.json \
                  "$API/downloadclient/$id?forceSave=true" \
                  || echo "reconciler: downloadclient PUT failed"
              fi
            fi
          fi
          id=$((id + 1))
        done
      else
        echo "reconciler: adding Transmission download client"
        curl -sf -o /dev/null -X POST -H "$AUTH" -H "$CT" -d @/tmp/dc.json "$API/downloadclient" \
          || echo "reconciler: downloadclient POST failed"
      fi
    fi
  fi
  sleep 300
done
