#!/bin/sh
# Shared config-reconciler for Sonarr and Radarr. Mounted read-only at
# /scripts/reconcile.sh from the servarr-reconciler-script ConfigMap
# (generated by apps/kustomization.yaml). See docs/servarr.md.
#
# Required env (set per-service in each Deployment):
#   APIKEY          - *arr API key (servarr-apikeys secret)
#   TX_USER/TX_PASS - Transmission credentials (transmission-auth secret)
#   API_PORT        - 8989 (Sonarr) / 7878 (Radarr)
#   ROOT_FOLDER     - /tv (Sonarr) / /movies (Radarr)
#   CATEGORY_FIELD  - tvCategory (Sonarr) / movieCategory (Radarr)
#   CATEGORY_VALUE  - tv-sonarr (Sonarr) / radarr (Radarr)

API="http://localhost:${API_PORT}/api/v3"
AUTH="X-Api-Key: ${APIKEY}"
CT="Content-Type: application/json"

# Escape a value for embedding in a JSON string literal. Without this a
# Transmission password containing " or \ yields invalid JSON and the
# download-client POST fails silently (curl -sf swallows the 400).
json_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

TX_USER_JSON=$(json_escape "${TX_USER}")
TX_PASS_JSON=$(json_escape "${TX_PASS}")

cat > /tmp/dc.json <<JSON
{
  "enable": true,
  "protocol": "torrent",
  "priority": 1,
  "removeCompletedDownloads": true,
  "removeFailedDownloads": true,
  "name": "Transmission",
  "implementation": "Transmission",
  "implementationName": "Transmission",
  "configContract": "TransmissionSettings",
  "fields": [
    {"name": "host", "value": "transmission.default.svc.cluster.local"},
    {"name": "port", "value": 9091},
    {"name": "useSsl", "value": false},
    {"name": "urlBase", "value": "/transmission/"},
    {"name": "username", "value": "${TX_USER_JSON}"},
    {"name": "password", "value": "${TX_PASS_JSON}"},
    {"name": "${CATEGORY_FIELD}", "value": "${CATEGORY_VALUE}"}
  ]
}
JSON

while true; do
  if curl -sf -o /dev/null -H "$AUTH" "$API/system/status"; then
    if FOLDERS=$(curl -sf -H "$AUTH" "$API/rootfolder"); then
      echo "$FOLDERS" | grep -q "\"${ROOT_FOLDER}\"" || {
        echo "reconciler: adding ${ROOT_FOLDER} root folder"
        curl -sf -o /dev/null -X POST -H "$AUTH" -H "$CT" -d "{\"path\":\"${ROOT_FOLDER}\"}" "$API/rootfolder" \
          || echo "reconciler: rootfolder POST failed"
      }
    fi
    if CLIENTS=$(curl -sf -H "$AUTH" "$API/downloadclient"); then
      if echo "$CLIENTS" | grep -q 'Transmission'; then
        # The client already exists, so the POST above never runs. Reconcile the two
        # removal flags in place: without them nothing ever deletes a completed
        # download and downloads/complete grows without bound. See issue #728.
        id=1
        while [ "$id" -le 10 ]; do
          if DC=$(curl -sf -H "$AUTH" "$API/downloadclient/$id"); then
            if echo "$DC" | grep -q '"implementation"[[:space:]]*:[[:space:]]*"Transmission"'; then
              NEW=$(echo "$DC" \
                | sed -e 's|"removeCompletedDownloads"[[:space:]]*:[[:space:]]*false|"removeCompletedDownloads":true|' \
                      -e 's|"removeFailedDownloads"[[:space:]]*:[[:space:]]*false|"removeFailedDownloads":true|')
              if [ "$NEW" != "$DC" ]; then
                echo "reconciler: enabling completed/failed download removal on client $id"
                echo "$NEW" > /tmp/dc-patch.json
                curl -sf -o /dev/null -X PUT -H "$AUTH" -H "$CT" -d @/tmp/dc-patch.json \
                  "$API/downloadclient/$id?forceSave=true" \
                  || echo "reconciler: downloadclient PUT failed"
              fi
            fi
          fi
          id=$((id + 1))
        done
      else
        echo "reconciler: adding Transmission download client"
        curl -sf -o /dev/null -X POST -H "$AUTH" -H "$CT" -d @/tmp/dc.json "$API/downloadclient" \
          || echo "reconciler: downloadclient POST failed"
      fi
    fi
  fi
  sleep 300
done
