apiVersion: v1
kind: Service
metadata:
  name: authentik-worker
spec:
  selector:
    app: authentik-worker
  ports:
    - name: http
      port: 9000
      targetPort: 9000
    - name: metrics
      port: 9300
      targetPort: 9300
