apiVersion: v1
kind: Service
metadata:
  name: pve-exporter
  namespace: default
  labels:
    app: pve-exporter
spec:
  selector:
    app: pve-exporter
  ports:
    - port: 9221
      targetPort: 9221
      protocol: TCP
