#!/usr/bin/env bash
set -euo pipefail

SECRET_NAME="registry-auth"
PULL_SECRET="registry-pull"
NS="default"
HOST="registry.home.bstjohn.net"

AUTH_EXISTS=false
PULL_EXISTS=false
kubectl get secret "$SECRET_NAME" -n "$NS" >/dev/null 2>&1 && AUTH_EXISTS=true
kubectl get secret "$PULL_SECRET" -n "$NS" >/dev/null 2>&1 && PULL_EXISTS=true

if [ "$AUTH_EXISTS" = true ] && [ "$PULL_EXISTS" = true ]; then
  echo "Secrets $SECRET_NAME and $PULL_SECRET already exist, skipping"
  exit 0
fi

if [ "$AUTH_EXISTS" = true ] && [ "$PULL_EXISTS" = false ]; then
  # registry-auth was created on a prior (partially failed) run. Reuse its
  # puller password so both secrets stay consistent, and just create the
  # missing one.
  PULL_PASS=$(kubectl get secret "$SECRET_NAME" -n "$NS" \
    -o jsonpath="{.data['puller-password']}" | base64 -d)
  kubectl create secret docker-registry "$PULL_SECRET" -n "$NS" \
    --docker-server="$HOST" --docker-username=puller --docker-password="$PULL_PASS"
  echo "Created $PULL_SECRET (reused existing $SECRET_NAME)"
  exit 0
fi

gen() { tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 40 || true; }
CI_PASS=$(gen); PULL_PASS=$(gen)
if [ "${#CI_PASS}" -ne 40 ] || [ "${#PULL_PASS}" -ne 40 ]; then
  echo "ERROR: password generation failed" >&2; exit 1
fi

# zot v2.1.20 accepts bcrypt and SHA-crypt ($5$/$6$) htpasswd hashes
# (pkg/api/htpasswd.go). alpine/k8s ships no `htpasswd` binary, so try the
# SHA-512 crypt producers in order. Do NOT `apk add` inside a migration.
# Password is piped via stdin to each tool, never passed as argv, so it
# never appears in /proc/<pid>/cmdline.
hash_pw() {
  local out=""
  if command -v openssl >/dev/null 2>&1; then out=$(printf '%s\n' "$1" | openssl passwd -6 -stdin 2>/dev/null || true); fi
  if [ -z "$out" ] && command -v mkpasswd >/dev/null 2>&1; then out=$(printf '%s\n' "$1" | mkpasswd -m sha512 -s 2>/dev/null || true); fi
  if [ -z "$out" ] && command -v python3 >/dev/null 2>&1; then
    out=$(printf '%s\n' "$1" | python3 -c 'import crypt,sys; print(crypt.crypt(sys.stdin.readline().rstrip("\n"), crypt.mksalt(crypt.METHOD_SHA512)))' 2>/dev/null || true)
  fi
  case "$out" in '$6$'*) printf '%s' "$out" ;; *) return 1 ;; esac
}
CI_HASH=$(hash_pw "$CI_PASS") || { echo "ERROR: no SHA-512 crypt tool; see docs/registry.md" >&2; exit 1; }
PULL_HASH=$(hash_pw "$PULL_PASS") || { echo "ERROR: no SHA-512 crypt tool; see docs/registry.md" >&2; exit 1; }

# OIDC client secret is generated by 0004, which runs first (lexicographic order).
OIDC_SECRET=$(kubectl get secret authentik-secrets -n "$NS" \
  -o jsonpath="{.data['REGISTRY_OIDC_CLIENT_SECRET']}" 2>/dev/null | base64 -d || true)
if [ -z "$OIDC_SECRET" ]; then
  echo "ERROR: REGISTRY_OIDC_CLIENT_SECRET missing from authentik-secrets (0004 must run first)" >&2
  exit 1
fi

printf '{"clientid":"registry","clientsecret":"%s"}\n' "$OIDC_SECRET" > /tmp/oidc.json
printf '%s\n%s\n' "ci:${CI_HASH}" "puller:${PULL_HASH}" > /tmp/htpasswd

kubectl create secret generic "$SECRET_NAME" -n "$NS" \
  --from-file=htpasswd=/tmp/htpasswd \
  --from-file=oidc.json=/tmp/oidc.json \
  --from-literal=ci-username=ci \
  --from-literal=ci-password="$CI_PASS" \
  --from-literal=puller-username=puller \
  --from-literal=puller-password="$PULL_PASS"

kubectl create secret docker-registry "$PULL_SECRET" -n "$NS" \
  --docker-server="$HOST" --docker-username=puller --docker-password="$PULL_PASS"

rm -f /tmp/oidc.json /tmp/htpasswd
echo "Created $SECRET_NAME and $PULL_SECRET"
