apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garden-photos
  labels:
    app: garden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
