apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: godaddy-webhook
  namespace: flux-system
spec:
  interval: 1h
  url: https://fred78290.github.io/cert-manager-webhook-godaddy
