---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-local-config-pvc
  labels:
    app: transmission
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
