apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mealie
  name: mealie-data
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
