apiVersion: v1
kind: Service
metadata:
  name: grafana-github-alerts
  namespace: default
spec:
  selector:
    app: grafana-github-alerts
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
