apiVersion: v1
kind: Secret
metadata:
    name: grafana-webhook-shared-secret
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:YaO1dl9QxlS2kh2adaPSg1jCNEWxEbSwcc2Mmq5Tf+NFjlMczGX3egTfjPjjIMv6rdtgWyWXqIDNblP+4cg1DQ==,iv:7gWqKd6PPhYbauR7xWK/MUlEf0uHRd0VOcLM4ct2rMg=,tag:V55j7czWg2+3QyLz/VoRaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tuhxkp7ma9xfzpsan63c94qdn4c48v6f0z5uak7updragn8ep9q0y3xfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyc00xNU5zaEhRT3BHcE1F
            K1dEQVdVaWVOczRCdVV2WHNoUnBQY3VONFVvClF6L3d5ZnJ2R0tFZzJERUZROE9L
            V0VSWEUvMGRMQnp5aSt0TWpSTXZic28KLS0tIEZVNEd4QUI3RE8rZGF1WUQySGlu
            Wnp1dkZ4RnlFY2FZb2hzT0ZEaWZESmcK2YBRmfH7BbC3JZIJnD2wmDw7xDlBA0Yq
            8hFBOYzYGSIXjYO5QolGIHpT9JJOnCc12iGkIyNvldTjx/o5u5b8gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T21:58:53Z"
    mac: ENC[AES256_GCM,data:Bsrw2Wm0qh2Xqxx39WpUO2zOVcfTwDYYbpZTuqWZhVWC3lpjxTIFb7E0tjriF5NMDfETceLB+b5HtOq875lNAPdRs8Yyf4EplkQzPwsme0cpDC+UuVpwY33l7fkA7aSWgFctA3TmQclsvOWki3VzFNaFGaNmEcfYzpuAJHv2f6U=,iv:NO+eanhvdRhbtYXJ1eudxDwKQWv8oTIkq7I4aLq4C2Q=,tag:Bc4hM4yEm3Nwi6aAKhJmqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
