apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: truenas-gate-wake-webhook
    namespace: default
stringData:
    wake-webhook.conf: ENC[AES256_GCM,data:1S7q2rBCaUQvoaxCc+UdhKDZBU98Lei0z27XIQcEAuiQh1l5dj8LcZmO9lNKOGgFDeZHl2MtrqaS27M6cFfaVKr2EtyMZ6S218urW/4sMTZtVxZHm6b/cjLmf339CLyjDhvM+M1t/EAVUPy7UfD82jDB76RGtY00BizBgieOHOrNoBWEH26OZwWNzNwQgSowsJd7u7qs+ACwzdcpJFWUpnV9Lk3YPNiQepbo6kcZtzlj+mL51+17zlKrZwAXmMK8P3DqA/8YO4k53qAIvlG8ZvT1Yv6sVLC2Eb5AeP9GPw1stHckv10AAIyPb/M+54qinFrakMjen4Z/dpoR1saF42NegNPO12afVVMsE0aX5LFzqpsPDirkp41FmawZKMGtIBO6FJb6YuMCguFhsft3uLvRe1k0r5fOn6DqTvFmlPtbNN/n0BaEQkEx59dkJnKVKJ5oLCRR/P+ZLLROof/I+0kN9Zjv1CUgdWvww3pAxRbnY2wDE/q/Ml8E0eZPPAMXP3egoyCpx6ymBRMHcUBvx5Yez10sj9rX/xfBlmKvSwVjeb3ll24eIX/VBna9VMGSlPr7AUyRsYMQsWhc/Rd35QVkNKfWQqGCRfLWxKUauulvqtA+Vj2z9mhxZAJc0rwKzd/y/+KK5FkRa9Z79zDL+fK8bg4DNHacTFoOdsBRaGZn/mF5ivwYHSZDgOLJBSBvdwltZte3nE5uCFeQC9GzvBtogmJovnc+zpK8r2PZrla1mmxMd/jIWw/mu8FABkHBGDj8IcXx5oD+AcIA0kBL8dZvmTiwi7i6tAN++zrrhK5mj6akx8OPmAkFQbnrgbisHYxKoKXXe1QxRNsVmkWiIy0WAKFtpGFmq29++HSs1qWkrBCigxzQ4LhKPJPI+UjRtMv9EswTyNECoRBGgikWH1MEcSKYM5J9yXGUMFy0PNeO/akIJEj7TtYywwc3aJQCN2bccxze72dspaYEcADafZYW,iv:tHtrwwAUOPO1nvp4nABAJOElz5+P3TcpG2OborPg4EQ=,tag:t0pQP/NaiFcpHHmuPPaakg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tuhxkp7ma9xfzpsan63c94qdn4c48v6f0z5uak7updragn8ep9q0y3xfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ2haRE9VUnRwRkJpRFhq
            MXo0NytTYWtkRGZoOGpJaVQ2SU5LMmxKZ0hNCndDbHpjT2Z6eVJnZzUvZHVtRlIz
            YnZ4aWFoMUVGSmIwWTFvZUNrTTNUM0EKLS0tIEdQUEJNVXBwSEdlbUlYNHZBRVpu
            cHdWYll3TlRIK2tFYjA1M2xHZHdxUXMKa7cWojcsIBbwmPZQP0S41UDLsLQav0HT
            kUBRDUY3gBl2JOJGYxzwukF/N4/Q9VJonbtFyanTNSe0eR0xAeZ0kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T09:03:22Z"
    mac: ENC[AES256_GCM,data:sCtEHMsCErmsUkjZLBQ//xpN8Kfwt7h2p2WgByjANRA9FhK44vrRn2mvr0sSq3k/VpSLUiaOzX9gJS672axWJnrsT64RbjXp5g03xqdmu/xcFukpT66yMnFKDfbOr9BFg7YsTj5HfcoQACDr+NOu2mP5oC7m2XzIHUlFsQmlOQY=,iv:oeLRHztbyjps5MBKz1CaAD5xheatF/v5gydr3hBAJcQ=,tag:P1FGu8dsFwAggZZfh+/eMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
