apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: bin-scraper-address
    namespace: default
stringData:
    postcode: ENC[AES256_GCM,data:KnPczqkfng==,iv:w67faji4sZLZWgv5o+8WEVmdG3Vv7COSV+USCPefWd4=,tag:7uphnZXAVgyG8mBcsNx6dA==,type:str]
    address-match: ENC[AES256_GCM,data:Hg3jXJFlowW6zNk=,iv:jiSlRerNQJNiFv6E+roeLkAo7UAaly5NTq1hTYFjlXA=,tag:RciPhDghkHtx//OM2pwmBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tuhxkp7ma9xfzpsan63c94qdn4c48v6f0z5uak7updragn8ep9q0y3xfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBra3FSTmlaQVNkUmllQTBU
            RmVWSlRybmtUWm14YkRIWm5xaFMrUkJsMDMwCmdvTHRBdk1hd3BtM0tvZk44d2da
            Z0JvZDRUbW1PcVYydy8vQmVaVVp2V2sKLS0tIFRtUzgxcjN6SFgxR2JRM3d0K0lx
            d2hZVmxOWmcvMSt5d1hMZlgzNmVRSkUKcPM33/efMNpnstHU3vhPT7DLGLoj5+Dg
            +dnNXvXVpM1xNpGNp9Pc7BqhuvQiq3poFsGl05Wm+FLcoym13HJVNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T15:22:16Z"
    mac: ENC[AES256_GCM,data:HDaUlyNeGxcm2WjwueUHlWjEkA5yB9OwG/y1jdRoFLwMUtiWtKSEZrFnqCyBgai/XkKM4LvZ+aSlAeYJfHKm08U7pByHvrPOkD6DvOLFUHIombBG4/L7Ik+Pc6q700wjEp7XHAw8ySrIZMWx+Upb7P6P78u7Dcjh92uhkDsgJTQ=,iv:RAcOEHKkPLz+EKKnlw0KmrM7x5hoSwCer86sukH7oqc=,tag:ykY4q8zI2zic06Bj+549QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
