apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bin-scraper-data
  labels:
    app: bin-scraper
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
