---
apiVersion: v1
kind: Secret
metadata:
  name: readonly-user-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: readonly-user
type: kubernetes.io/service-account-token
