---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
  labels:
    app: jellyseerr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
