apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - service-ssh.yaml
  - ingress.yaml
  - backup-pvc.yaml
  - cronjob-backup.yaml
  - cronjob-backup-offsite.yaml
