apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: datasette-ingress-from-traefik-only
  labels:
    app: datasette
spec:
  podSelector:
    matchLabels:
      app: datasette
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values: [gatus]
      ports:
        - protocol: TCP
          port: 8001
