apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datasette-data
  labels:
    app: datasette
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
