apiVersion: v1
kind: ServiceAccount
metadata:
  name: datasette-sync
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datasette-sync
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: [deployments]
    resourceNames: [datasette]
    verbs: [get, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datasette-sync
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: datasette-sync
subjects:
  - kind: ServiceAccount
    name: datasette-sync
    namespace: default
