apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr-pull
  namespace: default
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:ylwfBrhIzdyaFNlCrD3gV8W1aZ8YEOGn0s4JO+00EER7uIJWSaCXTdOXIH34NvUyas2VUg9UojEeUdRd5l6pCcA/q7ALC9koeovT9L82rhoK/yGI3iEFJtqnklwyvmyloHQ=,iv:7rizpdBjZEFlJ7aRwAph+6ccod5exQuc4BlnX84yUqA=,tag:g2Ei8B4S0Iknr337qXebXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tuhxkp7ma9xfzpsan63c94qdn4c48v6f0z5uak7updragn8ep9q0y3xfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQXVGMjY5T2FOVGN2ZHAy
            UE1aakNBZWE1dUIyMjh1cDNITlI1Q1FRSlVrClFWaFZ4M0tNRGNRMnN1dmRpN3Ew
            QmEwVnplSjQ4K1RvdVFseWhCZWkyemsKLS0tIDdsaW1lOXNmNisza0NLRDZuODRK
            YWUwMDJFcHZaRTk0YVBySWhrQWs4cGcKY56AY77/s41VY7r21C9hWxRYq6gGiOIF
            Z9pRSivmK1KX1gpA8rMOTM/qJ3zsz2dDDs5jRl8i+atPL5UZxR4TRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T20:42:40Z"
    mac: ENC[AES256_GCM,data:D/O/N0AHkFpSTZAAAzze3TTpr14wTlOwu6nU7sWcYvLSSHQ6QryqbHqGGCTTA/wF5Q85K5/BiirIlWUZB9L+AmwRfPw/dmuMefy1Qarfp8dlmxG+cZbx4xJD4oUk0EWYy/wHT9HB/9ZA+EknheBzJEOZdhO6i+igO3W7i0m31mk=,iv:8ok0RXVUbLaOUYiPZkns+pYoyxSsG1GG/Q5ebAaq6IU=,tag:mqSw3p/kvt0dz9o/DUNgQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
