---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-local-config-pvc
  labels:
    app: bazarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
